config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index, :show] do
    member do
      post 'bet/(:team)', to: 'games#bet', as: 'bet'
    end
  end
  post 'games', to: 'games#time_travel'
  post 'username', to: 'games#username'

  root to: 'games#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bet.rb
class Bet
  include Mongoid::Document
  field :bet_on, type: String
  field :user, type: String
  scope :user_bet, ->(user) { where(user: user) }
  scope :equipe_bet, ->(equipe) { where(bet_on: equipe) }
  embedded_in :game
end

app/models/game.rb
class Game
  include Mongoid::Document
  embeds_many :bets
  default_scope { order_by(date: 'asc') }
  scope :upcoming, ->(at_date) { where(:date.gte => at_date) }
  scope :finished, ->(at_date) { where(:date.lt => at_date) }
  field :equipea, type: String
  field :equipeb, type: String
  field :date, type: Date
  field :scorea, type: String
  field :scoreb, type: String


  def bets_on_equipea
    bets.where(bet_on: equipea).count
  end

  def bets_on_equipeb
    bets.where(bet_on: equipeb).count
  end

  def score
    "#{scorea} - #{scoreb}"
  end

  def equipea_color
    return 'bg-success' if equipea_win?
  end

  def equipeb_color
    return 'bg-success' if equipeb_win?
  end

  def equipea_win?
    scorea > scoreb
  end

  def equipeb_win?
    scoreb > scorea
  end

  def winner
    return equipea if scorea > scoreb
    return equipeb if scoreb > scorea
    nil
  end

  def winning_bet(user)
    bets.user_bet(user).equipe_bet(winner)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :bet]
  before_action :set_username

  def index
    date_from_param = date_filter_params[:travel_date].to_date unless date_filter_params[:travel_date].nil?
    @travel_date = date_from_param || session[:travel_date]&.to_date || Date.today
    session[:travel_date] = @travel_date

    @past_games = PastGameDecorator.wrap_collection(Game.finished(@travel_date), @username)
    @upcoming_games = UpcomingGameDecorator.wrap_collection(Game.upcoming(@travel_date), @username)

    @bet_won = Game.finished(@travel_date).map { |g| g.winning_bet(@username) }.flatten.count
    @travel_direction = date_filter_params[:travel_direction] || 'forward'
  end

  def time_travel
    redirect_to(games_url(date_filter: date_filter_params))
  end

  def show
  end

  def username
    session[:username] = user_params[:name]
    redirect_to(games_url(date_filter: date_filter_params))
  end

  def bet
    if session[:username].nil?
      redirect_to games_path, notice: 'Please set username!'
    elsif @game.bets.user_bet(@username).any?
      redirect_to game_path(@game.id), notice: 'You already bet'
    else
      @game.bets << Bet.new(bet_on: params[:team], user: @username)
      redirect_to game_path(@game.id)
    end
  end

  private

  def set_game
    game = Game.find(params[:id])
    if game.date < Date.parse(session[:travel_date])
      @game = PastGameDecorator.wrap(game, @username)
    else
      @game = UpcomingGameDecorator.wrap(game, @username)
    end
  end

  def set_username
    @username = session[:username]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def game_params
    params.require(:game).permit(:equipea, :equipeb, :date, :scorea, :scoreb)
  end

  def user_params
    params.require(:user).permit(:name)
  end

  def date_filter_params
    params.fetch(:date_filter, {}).permit(:travel_date, :travel_direction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_game.html.erb
<tr class="<%= game.row_style %>">
  <td><%= game.date %></td>
  <td><%= game.equipea %></td>
  <td><%= game.score %></td>
  <td><%= game.equipeb %></td>
  <td><%= link_to game.show_title, game %></td>
</tr>

app/views/games/_games_table.html.erb
<table class="table table-hover text-center">
  <thead>
    <tr>
      <th>Date</th>
      <th>Equipe a</th>
      <th>Score</th>
      <th>Equipe b</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <%= render games %>
  </tbody>
</table>

app/views/games/index.html.erb
<div class="container">
  <div class="row align-items-center justify-content-center">
    <div class="col-sm">
    <p>Running on: <%= Socket.gethostname %></p>
    </div>
    <div class="col-sm">
      <% if @username.nil? %>
        <%= form_for(:user, url: username_path, method: 'post', remote: true, html: {class: 'form-inline justify-content-center mb-2'}) do |f| %>
          <%= f.text_field(:name, value: @username, class: 'form-control bg-light', placeholder: 'Set your username') %>
          <%= f.submit 'Save', class: 'btn btn-light' %>
        <% end %>
      <% else %>
        <div class="text-center">
          <p class="font-weight-bold"><%= @username.capitalize %> you won <%= pluralize(@bet_won, 'bet') %></p>
        </div>
      <% end %>
    </div>
    <div class="col-sm justify-content-center">
    </div>
  </div>
  <div class="row align-items-center justify-content-center">
    <div class="col-sm ">
      <div>
        <%= image_tag("doloreanBTTC.png", class: @travel_direction, width: '150') %>
      </div>
    </div>
    <div class="col-sm justify-content-center">
      <div class="form-inline justify-content-center">
        <%= form_for(:date_filter, method: 'post', remote: true) do |f| %>
          <%= f.date_field(:travel_date , value: @travel_date - 1.day, class: 'form-control bg-light d-none', readonly: true ) %>
          <%= f.hidden_field(:travel_direction, value: 'backward') %>
          <%= f.submit '&lt;'.html_safe, class: 'btn btn-light' %>
        <% end %>
        <p class="form-control mb-0"><%= time_tag @travel_date %></p>
        <%= form_for(:date_filter, method: 'post', remote: true) do |f| %>
          <%= f.date_field(:travel_date , value: @travel_date + 1.day, class: 'form-control bg-light d-none', readonly: true ) %>
          <%= f.hidden_field(:travel_direction, value: 'forward') %>
          <%= f.submit '&gt;'.html_safe, class: 'btn btn-light' %>
        <% end %>
      </div>
    </div>
    <div class="col-sm justify-content-center">
    </div>
  </div>

  <br>

  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <h3 class="text-center">Past games</h2>
        <%= render 'games_table', games: @past_games %>
      </div>
      <div class="col">
        <h3 class="text-center">Upcoming games</h2>
        <%= render 'games_table', games: @upcoming_games %>
      </div>
    </div>
  </div>

app/views/games/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-auto">
      <%= link_to '&lt; back'.html_safe, games_path %>
      <h5>Game will be on: <%= @game.date %></h5>
      <table class="table text-center">
        <thead>
          <tr>
            <th>Equipe a</th>
            <th>Score</th>
            <th>Equipe b</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td class="<%= @game.equipea_color %>"><%= @game.equipea %></td>
            <td><%= @game.score %></td>
            <td class="<%= @game.equipeb_color %>"><%= @game.equipeb %></td>
          </tr>
          <% if @game.bet_allowed? %>
            <tr>
              <td>
                <%= link_to "Bet #{@game.equipea} will win", bet_game_path(@game.id, @game.equipea), method: 'post', class: 'btn btn-success' %>
              </td>
              <td></td>
              <td>
                <%= link_to "Bet #{@game.equipeb} will win", bet_game_path(@game.id, @game.equipeb), method: 'post', class: 'btn btn-success' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>


      <h4>Bets</h4>
      <% if @game.bets.any? %>
        <table class="table text-center">
          <thead>
            <tr>
              <th>User</th>
              <th>will win?</th>
            </tr>
          </thead>

          <tbody>
            <% @game.bets.each do |bet| %>
              <tr>
                <td><%= bet.user %></td>
                <td><%= bet.bet_on %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        No bet yet!
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>betting</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid bg-color">
    <h1 class="text-center">Back to the future betting!</h1>
    <% if flash.any? %>
      <div class="container">
        <div class="row justify-content-md-center">
          <div class="col-md-auto">
            <p id="notice" class="alert alert-info"><%= notice %></p>
          </div>
        </div>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>